#ifndef KERNEL_DRIVERS_STORAGE_ATA_H
#define KERNEL_DRIVERS_STORAGE_ATA_H

#include <kernel/drivers/storage/block_device.h>
#include <stdint.h>

#define KERNEL_APPFS_START_LBA 0u
#define KERNEL_APPFS_DIRECTORY_SECTORS 16u
#define KERNEL_APPFS_APP_SECTOR_COUNT 131072u
#define KERNEL_PERSIST_START_LBA (KERNEL_APPFS_START_LBA + KERNEL_APPFS_DIRECTORY_SECTORS + KERNEL_APPFS_APP_SECTOR_COUNT)
#define KERNEL_PERSIST_SECTOR_SIZE 512u
#define KERNEL_PERSIST_SECTOR_COUNT 640u
#define KERNEL_PERSIST_MAX_BYTES (KERNEL_PERSIST_SECTOR_SIZE * KERNEL_PERSIST_SECTOR_COUNT)

int kernel_ata_init(void);
void kernel_storage_init(void);

#endif
