#!/usr/bin/env python3
import argparse
import csv
from pathlib import Path


def parse_manifest(path: Path):
    entries = []
    with path.open("r", encoding="utf-8") as handle:
        reader = csv.reader(handle, delimiter="\t")
        for row in reader:
            if not row or not row[0] or row[0].startswith("#"):
                continue
            if len(row) < 4:
                raise SystemExit(f"invalid manifest row: {row!r}")
            name = row[0].strip()
            build_var = row[1].strip()
            shell_visible = row[2].strip() == "1"
            prefer_external = row[3].strip() == "1"
            stub_paths = []
            if len(row) >= 5 and row[4].strip():
                stub_paths = [item.strip() for item in row[4].split(",") if item.strip()]
            entries.append(
                {
                    "name": name,
                    "build_var": build_var,
                    "shell_visible": shell_visible,
                    "prefer_external": prefer_external,
                    "stub_paths": stub_paths,
                }
            )
    return entries


def unique_in_order(values):
    seen = set()
    ordered = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        ordered.append(value)
    return ordered


def write_text(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def emit_make(entries):
    build_bins = [f"$({entry['build_var']})" for entry in entries if entry["build_var"]]
    lines = [
        "# Auto-generated by tools/generate_app_catalog.py",
        "APP_CATALOG_APP_BINS := " + " ".join(build_bins),
        "",
    ]
    return "\n".join(lines)


def emit_header(entries):
    shell_commands = unique_in_order(
        entry["name"] for entry in entries if entry["shell_visible"]
    )
    prefer_external = unique_in_order(
        entry["name"] for entry in entries if entry["prefer_external"]
    )
    stub_paths = unique_in_order(
        path for entry in entries for path in entry["stub_paths"]
    )

    def string_array(name, values):
        lines = [f"static const char *const {name}[] = {{"]
        for value in values:
            lines.append(f'    "{value}",')
        lines.append("};")
        lines.append(
            f"#define {name.upper()}_COUNT (sizeof({name}) / sizeof({name}[0]))"
        )
        lines.append("")
        return "\n".join(lines)

    parts = [
        "/* Auto-generated by tools/generate_app_catalog.py */",
        "#ifndef VIBE_GENERATED_APP_CATALOG_H",
        "#define VIBE_GENERATED_APP_CATALOG_H",
        "",
        string_array("g_app_catalog_shell_commands", shell_commands),
        string_array("g_app_catalog_prefer_external", prefer_external),
        string_array("g_app_catalog_stub_paths", stub_paths),
        "#endif",
        "",
    ]
    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--mk")
    parser.add_argument("--header")
    args = parser.parse_args()

    entries = parse_manifest(Path(args.manifest))
    if args.mk:
        write_text(Path(args.mk), emit_make(entries))
    if args.header:
        write_text(Path(args.header), emit_header(entries))


if __name__ == "__main__":
    main()
